<?php
/** @package Webshop::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("OrderDetailsMap.php");

/**
 * OrderDetailsDAO provides object-oriented access to the order_details table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Webshop::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class OrderDetailsDAO extends Phreezable
{
	/** @var string */
	public $Id;

	/** @var double */
	public $Amount;

	/** @var double */
	public $Price;

	/** @var int */
	public $Quantity;

	/** @var string */
	public $OrderId;

	/** @var int */
	public $ProductId;


	/**
	 * Returns the foreign object based on the value of OrderId
	 * @return Order
	 */
	public function GetOrder()
	{
		return $this->_phreezer->GetManyToOne($this, "ORDER_DETAIL_ORD_FK");
	}

	/**
	 * Returns the foreign object based on the value of ProductId
	 * @return Product
	 */
	public function GetProduct()
	{
		return $this->_phreezer->GetManyToOne($this, "ORDER_DETAIL_PROD_FK");
	}


}
?>