<?php
/** @package Webshop::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProductMap.php");

/**
 * ProductDAO provides object-oriented access to the product table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Webshop::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProductDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Name;

	/** @var float */
	public $Price;

	/** @var int */
	public $CategoryId;


	/**
	 * Returns a dataset of OrderDetails objects with matching ProductId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetOrderDetailss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "ORDER_DETAIL_PROD_FK", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of CategoryId
	 * @return Category
	 */
	public function GetCategory()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_product_category");
	}


}
?>